spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:users_db}
    username: ${DB_USERNAME:users_service}
    password: ${DB_PASSWORD:users_service_password}
server:
  error:
    whitelabel:
      enabled: false